/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "pointing-poker-frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "pointing-poker-http-api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "pointing-poker-table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "pointing-poker-ws-api": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}