/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "johnWhaley-poker-pokerTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "johnwhaley-poker-frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "johnwhaley-poker-httpApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "johnwhaley-poker-wsApi": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}